apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-hook
rules:
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-hook
subjects:
- kind: User
  name: keptn-hook
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: keptn-hook
  apiGroup: rbac.authorization.k8s.io